using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using System;
using NSwag;
using Microsoft.AspNetCore.Http;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json.Converters;
using System.Net.Http;
using System.Net;
using Microsoft.AspNetCore.StaticFiles;
using System.Threading.Tasks;
using NSwag.Generation.Processors;
using NSwag.Generation.Processors.Contexts;

public static class SwaggerExtendions
{
    //generating swagger and configuring settings
    public static void AddAutoGeneratedSwagger(this IServiceCollection services)
    {
        try
        {
            services.AddOpenApiDocument(c =>
            {
                c.Version = "";
                c.Title = $"Swagger";
                c.Description = "";
                c.DocumentProcessors.Add(new SwaggerFieldsDP());
                c.SchemaProcessors.Add(new SwaggerKnownTypesSP());
                c.DocumentProcessors.Add(new SwaggerExtendDP());
                c.OperationProcessors.Add(new SwaggerRequestExamplesOP());
                c.GenerateCustomNullableProperties = true;
                c.GenerateKnownTypes = false;
                c.GenerateAbstractSchemas = true;
                c.SerializerSettings = new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() };
                c.SerializerSettings.Converters.Add(new StringEnumConverter());
            });
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Cant Run Swagger - AddAutoGeneratedSwagger - {ex}");
        }
    }

    //generating swagger and configuring settings
    public static void UseAutoGeneratedSwagger(this IApplicationBuilder app)
    {
        try
        {
            app.Use(async (ctx, next) =>
            {
                Func<string, Func<string, string>?, Task> getFileAndResponse = async (string filePath, Func<string,string>? modifyContent) =>
                {
                    HttpClientHandler clientHandler = new HttpClientHandler();
                    ServicePointManager.Expect100Continue = false;
                    ServicePointManager.ServerCertificateValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;
                    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls13 | SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
                    clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => true;
                    var httpClient = new HttpClient(clientHandler);
                    var res = await httpClient.GetAsync(filePath);
                    new FileExtensionContentTypeProvider().TryGetContentType(filePath, out var contentType);
                    ctx.Response.Headers["Content-Type"] = contentType;
                    var content = await res.Content.ReadAsStringAsync();
                    if (modifyContent != null)
                    {
                        content = modifyContent(content);
                    }
                    await ctx.Response.WriteAsync(content);
                };
                try
                {
                    var path = ctx.Request.Path.Value;
                    if (path == "/" || path == "/api")
                    {
                        ctx.Response.Redirect("./api/swagger/index.html?url=./swagger.json");
                        return;
                    }
                    if (path == "/swagger.json")
                    {
                        await getFileAndResponse("http://localhost:5000/api/swagger/swagger.json", null);
                        return;
                    }
                    else if (path!.StartsWith("/api/swagger") && !path.EndsWith("swagger.json"))
                    {
                        // by bar nuri gal maniak
                        var filePath = "https://raw.githubusercontent.com/swagger-api/swagger-ui/master/dist/" + ctx.Request.Path.Value!.Split("/").Last();
                        await getFileAndResponse(filePath, content => 
                        {
                            content = content.Replace("https://petstore.swagger.io/v2/swagger.json", "./swagger.json");
                            return content;
                        });
                        return;
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"UseAutoGeneratedSwagger Error - {ex}");
                }
                await next.Invoke();
            });
            app.UseOpenApi(c =>
            {
                c.Path = "/api/swagger/swagger.json";
                c.PostProcess = (document, request) =>
                {
                    document.Servers.Clear();
                    try
                    {
                        var url = request.GetTypedHeaders().Referer.AbsoluteUri;
                        document.Servers.Add(new OpenApiServer { Url = url.Split("/api").ToList().FirstOrDefault() });
                        document.Servers.Add(new OpenApiServer { Url = url });
                    }
                    catch { }
                    document.Servers.Add(new OpenApiServer { Url = "/" });
                    document.Servers.Add(new OpenApiServer { Url = "/api" });
                    try
                    {
                        document.Servers.Add(new OpenApiServer { Url = request.GetTypedHeaders().Host.Value });
                    }
                    catch { }
                    document.Servers.Add(new OpenApiServer { Url = request.PathBase });
                    //document.Servers.Add(new OpenApiServer { Url = request.Headers });
                };
            });

            app.UseSwaggerUi3(c =>
            {
                c.DocExpansion = "list";
                c.DocumentPath = "./swagger.json"; //fix relative paths
                c.Path = "/api/swagger";
            });
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Cant Run Swagger - UseAutoGeneratedSwagger - {ex}");
        }
    }
}